odq-8: Dead-letter queue handler started to process INPUTQ(&3).
odq-9: Dead-letter queue handler ending.
odq-10: Usage:  amqsdlq [-u Userid] [QName[QMgrName]] [-c].
odq-33: Dead-letter queue message not prefixed by a valid MQDLH.
odq-34: Dead-letter queue handler unable to put message: Rule &1 Reason &2.
odq-65: Unable to connect to queue manager(&3) : CompCode = &1 Reason = &2.
odq-66: Unable to open queue manager: CompCode = &1 Reason = &2.
odq-67: Unable to inquire on queue manager: CompCode = &1 Reason = &2.
odq-68: Unable to close queue manager: CompCode = &1 Reason = &2.
odq-69: Unable to open dead-letter queue(&3) for browse: CompCode = &1 Reason = &2.
odq-70: Unable to close dead-letter queue: CompCode = &1 Reason = &2.
odq-71: Integer parameter(&2) outside permissable range for &3 on line &1.
odq-72: Unable to get message from dead-letter queue: CompCode = &1 Reason = &2.
odq-73: Unable to commit/backout action on dead-letter queue: CompCode = &1 Reason = &2.
odq-80: No valid input provided to runmqdlq.
odq-81: Unable to obtain private storage.
odq-82: Parameter(&3) exceeds maximum length on line &1.
odq-83: Duplicate parameter(&3) found on line &1.
odq-86: Error detected releasing private storage.
odq-87: Integer parameter(&3) outside permissable range on line &1.
odq-88: &1 errors detected in input to runmqdlq.
odq-89: Invalid combination of parameters to dead-letter queue handler on line &1.
odq-96: Unexpected failure while initializing process: Reason = &1.
odq-97: Unexpected failure while connecting to queue manager: CompCode = &1 Reason = &2.
odq-98: Unexpected error while attempting to open queue manager: CompCode = &1 Reason = &2.
odq-99: Unexpected error while inquiring on queue manager: CompCode = &1 Reason = &2.
odq-100: Unexpected error while attempting to close queue manager: CompCode = &1 Reason = &2.
odq-101: Unexpected failure while opening dead-letter queue for browse: CompCode = &1 Reason = &2.
odq-102: Unexpected error while closing dead-letter queue: CompCode = &1 Reason = &2.
odq-103: Unexpected error while getting message from dead-letter queue: CompCode = &1 Reason = &2.
odq-104: Unexpected error committing/backing out action on dead-letter queue: CompCode = &1 Reason = &2.
odq-105: Unable to disconnect from queue manager: CompCode = &1 Reason = &2.
